(0.000) None; args=None
(0.000) None; args=None
(0.000) None; args=None
(0.001) None; args=()
"GET / HTTP/1.1" 200 24659
"GET /static/js/mail.js HTTP/1.1" 304 0
"GET /static/css/static/images/signup.svg HTTP/1.1" 404 1708
Internal Server Error: /mail
Traceback (most recent call last):
  File "/home/griffin/.local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/griffin/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/griffin/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/griffin/Documents/home/landingpage/views.py", line 39, in send_contact_message
    resonse = json.loads(request.POST.get('data'))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
"POST /mail HTTP/1.1" 500 14934
(0.000) None; args=None
(0.000) None; args=None
(0.001) None; args=None
(0.000) None; args=()
"GET / HTTP/1.1" 200 24659
"GET /static/js/mail.js HTTP/1.1" 304 0
"GET /static/css/static/images/signup.svg HTTP/1.1" 404 1708
"GET /static/images/favicon-2.png HTTP/1.1" 200 930
Internal Server Error: /mail
Traceback (most recent call last):
  File "/home/griffin/.local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/griffin/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/griffin/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/griffin/Documents/home/landingpage/views.py", line 39, in send_contact_message
    resonse = json.loads(request.POST.get('data'))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
"POST /mail HTTP/1.1" 500 14937
(0.000) None; args=None
(0.000) None; args=None
(0.000) None; args=None
(0.001) None; args=()
(0.003) None; args=None
(0.000) None; args=None
(0.001) None; args=None
(0.000) None; args=()
"GET / HTTP/1.1" 200 24659
"GET /static/css/static/images/signup.svg HTTP/1.1" 404 1708
"GET /static/images/favicon-2.png HTTP/1.1" 200 930
Internal Server Error: /mail
Traceback (most recent call last):
  File "/home/griffin/.local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/griffin/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/griffin/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/griffin/Documents/home/landingpage/views.py", line 39, in send_contact_message
    resonse = json.loads(request.POST.get('data'))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
"POST /mail HTTP/1.1" 500 14968
"GET / HTTP/1.1" 200 24659
"GET /static/css/styles.css HTTP/1.1" 304 0
"GET /static/js/mail.js HTTP/1.1" 304 0
"GET /static/css/static/images/signup.svg HTTP/1.1" 404 1708
"GET /static/images/favicon-2.png HTTP/1.1" 200 930
Internal Server Error: /mail
Traceback (most recent call last):
  File "/home/griffin/.local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/griffin/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/griffin/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/griffin/Documents/home/landingpage/views.py", line 39, in send_contact_message
    resonse = json.loads(request.POST.get('data'))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
"POST /mail HTTP/1.1" 500 14968
Internal Server Error: /mail
Traceback (most recent call last):
  File "/home/griffin/.local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/griffin/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/griffin/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/griffin/Documents/home/landingpage/views.py", line 39, in send_contact_message
    resonse = json.loads(request.POST.get('data'))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
"POST /mail HTTP/1.1" 500 14968
(0.000) None; args=None
(0.000) None; args=None
(0.000) None; args=None
(0.000) None; args=()
"GET / HTTP/1.1" 200 24659
"GET /static/css/static/images/signup.svg HTTP/1.1" 404 1708
